apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eeuz44jrh-dotnet-basic
  janus-idp.io/tekton: eeuz44jrh-dotnet-basic
  backstage.io/kubernetes-id: eeuz44jrh-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eeuz44jrh-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
